### ISSUE TITLE
note: Jupyter scripts demonstrating how to access/process satellite data sources

### ISSUE THREAD

**Issue by 100ideas** [maxogden/goes-16-cira-geocolor#3]
@blaylockbk ([blog](http://home.chpc.utah.edu/~u0553130/Brian_Blaylock/home.html)) has a repository of python / jupyter scripts demonstrating how to access and process a variety of satellite data sources. 

"This Python notebook shows how to make the GOES-16 True Color product and plot it on different map projections using pyproj and Basemap": https://github.com/blaylockbk/pyBKB_v2/blob/master/BB_goes16/mapping_GOES16_data.ipynb

**Comment by blaylockbk** [comment]
FYI: This notebook, for Python 3, is the most up-to-date version: https://github.com/blaylockbk/pyBKB_v3/blob/master/BB_GOES/mapping_GOES16_TrueColor.ipynb
